### ISSUE TITLE
Pandoc

### ISSUE THREAD

**Issue by fdewes** [fdewes/rstudio-server-arm64#2]
The RStudio installer script also installs an x86 version of pandoc which does not work. Thus, PDF export of md file isn't working yet from within RStudio

**Comment by philippeckel** [comment]
@fdewes got a link to the line in the script?

**Comment by philippeckel** [comment]
Okay [found](https://github.com/rstudio/rstudio/blob/1f998005fcafe3372413e9eb0c0b0567c46056ce/dependencies/common/install-pandoc#L23) I guess

**Comment by fdewes** [comment]
almost, I think ;)
this dockerfile checks out the v1.1-patch branch of RStudio, your link is to master, right?

 v1.1-patch is the latest version I managed to compile on arm64. so we have to look in this branch, and then replace the pandoc install script with a blank file or skip it altogether etc.. 

pandoc (for arm64) is already installed earlier via apt. so this should hopefully work then

**Comment by fdewes** [comment]
fixen in dev branch

**Comment by fdewes** [comment]
fixed in dev branch
